---
- hosts: dbservers
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root

  tasks:
  - name: install dos2unix package
    yum: name=dos2unix state=present
    when: ansible_os_family == "RedHat"
  - name: ensure apache is at the latest version
    yum: pkg=httpd state=latest
  - name: write the apache config file
    template: src=/root/httpd/httpd.conf dest=/etc/httpd/httpd.conf
    notify:
    - restart apache
  - name: ensure apache is running
    service: name=httpd state=started
  handlers:
    - name: restart apache
      service: name=httpd state=restarted
